import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import BlogLogo from "../../Assets/Logo.png";
import SearchIcon from "../../Assets/SearchIcon.png";
import Image from "next/image";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" />
        <link
          href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400&family=Raleway&display=swap"
          rel="stylesheet"
        />
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}

export function NavBar() {
  return (
    <div className="px-20 py-5 flex flex-row justify-between">
      <div>
        <div className="flex gap-3">
          <div>
            <Image src={BlogLogo} alt="Blog logo" />
          </div>
          <div className="flex items-center font-bold text-2xl">Want2Know</div>
        </div>
      </div>
      <div className="flex gap-1">
        <div className="nav-bar-items">Blog</div>
        <div className="nav-bar-items">About</div>
        <div className="nav-bar-items">Contact Us</div>
        <div className="px-4 py-3 cursor-pointer">
          <Image src={SearchIcon} alt="search icon" />
        </div>
        <div className="purple-colored-button">Register</div>
        <div className="purple-colored-button">Login</div>
      </div>
    </div>
  );
}